### ISSUE TITLE
No intent gets called - "App Launch" does work

### ISSUE THREAD

**Issue by JustMeDaFaq** [alexa-js/alexa-app#333] opened 2018-04-08 17:18 UTC
Hi,
when using this interaction model:
```json
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "testintent",
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "TestIntent",
                    "slots": [],
                    "samples": [
                        "tomato say me hello world"
                    ]
                }
            ],
            "types": []
        }
    }
}
```

calling "testintent" in amazons test console/alexa simulator  correctly response with "You launched the app" (also console logs it), tho when then trying to invoke an intent by calling:
"tomato say me hello world" or "testintent tomato say me hello world", it seems that the endpoint does not get loaded/called actually. So, launching app works but intents doesnt, what am i doing wrong?

Using following nodejs code:
```js
var express = require("express");
var alexa = require("alexa-app");
var app = express();
var http = require("http"),
    https = require("https")
var alexaApp = new alexa.app("test");



alexaApp.express({
  expressApp: app,
  checkCert: false,
  debug: true
});

// now POST calls to /test in express will be handled by the app.request() function

// from here on you can setup any other express routes or middlewares as normal
app.set("view engine", "ejs");

alexaApp.launch(function(request, response) {
  console.log("yay");
  response.say("You launched the app!");
});


alexaApp.intent("TestIntent", {
    "utterances": [
      "tomato say me hello world"
    ]
  },
  function(request, response) {
      console.log("suc");
    response.say("Success!");
  }
);


var fs = require("fs");
var privateKey  = fs.readFileSync("./cer/privkey.pem", "utf8");
var certificate = fs.readFileSync("./cer/cert.pem", "utf8");
var credentials = {key: privateKey, cert: certificate};

var httpsServer = https.createServer(credentials, app);
httpsServer.listen(443);
```

Does someone may know, what im doing wrong?

**Comment by kobim** [comment] 2018-04-24 20:45
Hi @JustMeDaFaq,
Are you using the Alexa test simulator for testing?
Also, can you verify that your http server is running properly (and the certificate is valid) against the url you provided for your alexa skill?

**Comment by JustMeDaFaq** [comment] 2018-04-25 05:00
Yeah, certificate gets called.
Using Alexa Test Simulator, the new one on the Homepage.

Writing testintent works, it triggers the 'you launched the app" stuff correctly. (alexaApp.launch)

Just not when using alexaApp.intent :)

**Comment by kobim** [comment] 2018-04-25 05:31
If you are using the test simulator, can you take a look at the request it outputs in the Skill I/O tab?
Also, try to invoke `ask testintent to tomato say me hello world` as your command.

**Comment by JustMeDaFaq** [comment] 2018-04-26 18:59
ask testintent to tomato say me hello world => Works. How would i create a skill that just gets called by "tomato say me hello world " ?

**Comment by kobim** [comment] 2018-04-28 12:15
You can read more about it at [Invoking a Skill with a Specific Request ](https://developer.amazon.com/docs/custom-skills/understanding-how-users-invoke-custom-skills.html#cert-invoke-specific-request), but I'm afraid the closest you will get is `Alexa, say me hello world using tomato` if your _invocationName_ is *tomato* and your utterances include "say me hello world".

I'm pretty sure the usage of "connecting words" is there so Alexa could distinguish between different skills and route the request to the right one. If you want to elaborate on your use-case, we might be able to find the right utterance(s).

**Comment by kobim** [comment] 2018-10-24 07:32
Good news! as [Alexa's name-free interactions and skill discovery](https://developer.amazon.com/blogs/alexa/post/352e9834-0a98-4868-8d94-c2746b794ce9/improve-alexa-skill-discovery-and-name-free-use-of-your-skill-with-canfulfillintentrequest-beta) is in public beta, #378 will soon be merged and you will be able to resolve the issue you were having.

There's another issue (#367) with more links to developer documentation if you want to take a look.

**Comment by DeepakDonde** [comment] 2018-11-29 13:16
I am facing the same issue when using Alexa simulator. 
But when I test with **Manual JSON** it works!!!!

I think nothing is wrong with your code.I will check on real Alexa device just to make sure that the problem is only with Alexa simulator.

**Comment by FunnyDevs** [comment] 2018-12-05 08:37
I have same problem, only app launch is working.

**Comment by DeepakDonde** [comment] 2018-12-06 05:08
I am able to resolve this issue. The problem is with maintaining the session.When launch request fires, You need to keep session alive.
`shouldEndSession` is the Boolean parameter which is used to maintain session.
Below link explains how it works
[https://developer.amazon.com/docs/gadget-skills/keep-session-open.html](https://developer.amazon.com/docs/gadget-skills/keep-session-open.html)

**Comment by FunnyDevs** [comment] 2018-12-06 10:15
now it works! Thank you

**Closed** 2018-12-06 19:07 UTC
Labels: question
