### ISSUE TITLE
AMAZON.StopIntent

### ISSUE THREAD

**Issue by sohelsd** [alexa-js/alexa-app#234] opened 2017-05-01 17:00 UTC
I am having difficulty in hooking up the standard stop intent. While Amazon.HelpIntent works as expected, the stop intent never gets called, resulting in "Unable to generate request for your skill." error. 

Is there anything special that needs to be done for stop intents?

`app.intent('AMAZON.StopIntent', {
    "slots": {},
    "utterances": [
      "stop"
    ]
  },
  function(req, res) {
    console.log('app.AMAZON.StopIntent');
    res
    .say('Okay')
    .shouldEndSession(true);
  }
);`

**Comment by dblock** [comment] 2017-05-01 18:42
Where do you get this error?

Note sure what the issue is, but I have a stop intent in https://github.com/artsy/elderfield/blob/f4b9c430c176b6e60b299b1153277548efb75981/functions/artsy/index.js#L30.

**Comment by sohelsd** [comment] 2017-05-01 19:32
I am using the exact code but can't get it to invoke either on echo or service simulator on alexa dev portal. I get that error when using Service Simulator. Fortunately the HelpIntent seems to work fine.

**Comment by dblock** [comment] 2017-05-01 19:34
Maybe it's a simulator bug? Do you get it to work with an actual Alexa? Do you have the stop intent in the schema that you post to their UI?

**Comment by sohelsd** [comment] 2017-05-01 19:42
Same thing on Alexa device. AMAZON.StopIntent is just not honored in both (simulator or device) cases. I did verify that the intent is required and specified in the schema. I am using the new Skills builder beta. Not sure if that makes any difference.

**Comment by sohelsd** [comment] 2017-05-02 15:49
I decided to not use the Skill Builder beta and the stop intent is working fine. Potentially bug with the new skill builder.

**Comment by dblock** [comment] 2017-05-02 16:10
You should open an issue with Amazon. I'll close this one here.

**Closed by dblock** 2017-05-02 16:10 UTC
Labels: question

**Comment by theSuiGenerisAakash** [comment] 2018-11-28 10:42
Hey, check [this](https://stackoverflow.com/questions/52489579/alexa-lambda-not-returning-stopintent-after-saying-exit) one out... there's also the thing as said by the OP here about built-in utterances being mapped to their own intents which actually causes some problem and I did test it before writing here. You cannot have **cancel** in _StopIntent_, for instance.

I was also able to pinpoint the issue with the simulator as it was able to correctly map **CancelIntent** invocations but couldn't do so for **StopIntent**. The online skill builder might have some problem now since you mentioned.
